apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - policy-configmap.yaml
  - control-plane.yaml
  - edge.yaml
  - network-policy.yaml
  - disruption-budgets.yaml
