import { readFileSync } from 'node:fs'

import { describe, expect, it } from 'vitest'

import {
  parseBundleEnvelope,
  type Bundle,
} from '../src/bundle.js'
import {
  RouteMatcher,
  RouteMatcherError,
} from '../src/route-matcher.js'

const envelopeText = readFileSync(
  new URL(
    './fixtures/go-signed-envelope.json',
    import.meta.url,
  ),
  'utf8',
)

function readBundle(): Bundle {
  return parseBundleEnvelope(
    JSON.parse(envelopeText) as unknown,
  ).bundle
}

describe('route matcher', () => {
  it('selects the route generated by the Go compiler', () => {
    const matcher = new RouteMatcher(readBundle())

    const result = matcher.resolve(
      'GET',
      '/v1/orders/42',
    )

    expect(result.kind).toBe('matched')

    if (result.kind === 'matched') {
      expect(result.route.id).toBe('orders-read')
      expect(result.route.upstream).toBe(
        'http://127.0.0.1:9000',
      )
    }
  })

  it('normalizes the request method', () => {
    const matcher = new RouteMatcher(readBundle())

    const result = matcher.resolve(
      'get',
      '/v1/orders/order-123',
    )

    expect(result.kind).toBe('matched')

    if (result.kind === 'matched') {
      expect(result.route.id).toBe('orders-read')
    }
  })

  it('uses the default decision when no route matches', () => {
    const matcher = new RouteMatcher(readBundle())

    expect(
      matcher.resolve('POST', '/v1/orders/42'),
    ).toEqual({
      kind: 'default',
      decision: 'deny',
    })

    expect(
      matcher.resolve(
        'GET',
        '/v1/orders/42/extra',
      ),
    ).toEqual({
      kind: 'default',
      decision: 'deny',
    })
  })

  it('rejects inconsistent matcher metadata', () => {
    const unknownRouteBundle = readBundle()

    unknownRouteBundle.matchers[0]!.routeIds = [
      'missing-route',
    ]

    expect(
      () => new RouteMatcher(unknownRouteBundle),
    ).toThrow(RouteMatcherError)

    const unanchoredBundle = readBundle()

    unanchoredBundle.matchers[0]!.regex =
      '/v1/orders/[^/]+'

    expect(
      () => new RouteMatcher(unanchoredBundle),
    ).toThrow('must be anchored')

    const duplicateRouteBundle = readBundle()

    duplicateRouteBundle.routes.push({
      ...duplicateRouteBundle.routes[0]!,
    })

    expect(
      () => new RouteMatcher(duplicateRouteBundle),
    ).toThrow('duplicate route ID')
  })
})