apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - path: edge-rate-limit.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: shieldward-edge
    patch: |-
      - op: add
        path: /spec/egress/-
        value:
          to:
            - podSelector:
                matchLabels:
                  app.kubernetes.io/name: shieldward
                  app.kubernetes.io/component: rate-limit-store
          ports:
            - protocol: TCP
              port: 6379
